name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      # You can add inputs here if needed, or leave it empty for a simple manual trigger
      # For example:
      message:
        description: 'Optional message to include in the workflow run'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build # Assuming your build script generates static files in 'dist'

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Assuming your static files are in the 'dist' folder

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
